# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ww_MetaShapelib',
                'doc_host': 'https://lidar532.github.io',
                'git_url': 'https://github.com/lidar532/ww_MetaShapelib',
                'lib_path': 'ww_MetaShapelib'},
  'syms': {'ww_MetaShapelib.core': {'ww_MetaShapelib.core.foo': ('core.html#foo', 'ww_MetaShapelib/core.py')}}}
